feat: add base benchmark
gama-platform/gama.benchmark pull request #1
Opened 2023-08-25 10:36 UTC by WoodenMaiden

2023-08-28 06:26 UTC, RoiArthurB commented
Should remove and ignore every gradle wrappers (not needed in sources), which is everything `JMX/gradle*`

Also, please add a more descriptive description in the README (what tools needed, goal of the project, how to use, etc).

2023-08-31 03:02 UTC, RoiArthurB requested changes

2023-08-31 03:02 UTC, RoiArthurB commented on gama-workspace/.gitignore
Add `.built_in*`, `.gama_application_workspace*`,  `.metadata` and `gama-workspace/ListIteration/.settings`

2023-09-12 02:54 UTC, RoiArthurB requested changes

2023-09-12 02:54 UTC, RoiArthurB commented on README.md
> +- Java.
Please precise which one

2023-09-12 02:54 UTC, RoiArthurB commented on README.md
> +## Tools used
Missing Gradle in this list

2023-09-12 02:54 UTC, RoiArthurB commented on .github/workflows/bench.yml
> +          wget --show-progress https://github.com/gama-platform/gama/releases/download/1.9.1/GAMA_1.9.1_Linux_with_JDK.deb
Might have simplier workflow if using the GAMA version without JDK embedded and use system-wide JDK 17 ? 

Let me know if I'm correct on that.

2023-09-12 10:27 UTC, WoodenMaiden commented on .github/workflows/bench.yml
> +          wget --show-progress https://github.com/gama-platform/gama/releases/download/1.9.1/GAMA_1.9.1_Linux_with_JDK.deb
The reasoning behind picking the embedded JDK is to stick as much as possible to GAMA's requirements, if the JDK changes to another version of Gama or another vendor the benchmark will still run.

This may be some paranoid reasoning but hey, better safe than sorry :sweat_smile:.

2023-09-13 02:21 UTC, merged